-- MySQL Script generated by MySQL Workbench
-- 03/15/16 15:29:29
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`PISAC`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`PISAC` ;

CREATE TABLE IF NOT EXISTS `mydb`.`PISAC` (
  `idPISAC` INT NOT NULL AUTO_INCREMENT,
  `Ime` VARCHAR(45) NOT NULL,
  `Prezime` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPISAC`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Izdavac`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Izdavac` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Izdavac` (
  `idIzdavac` INT NOT NULL AUTO_INCREMENT,
  `Naziv` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idIzdavac`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Drzava`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Drzava` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Drzava` (
  `idDrzava` INT NOT NULL AUTO_INCREMENT,
  `Drzava` VARCHAR(45) NOT NULL,
  INDEX `idDrzava_idx` (`idDrzava` ASC),
  CONSTRAINT `idDrzava_Pisac`
    FOREIGN KEY (`idDrzava`)
    REFERENCES `mydb`.`PISAC` (`idPISAC`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idDrzava_Izdavac`
    FOREIGN KEY (`idDrzava`)
    REFERENCES `mydb`.`Izdavac` (`idIzdavac`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Knjiga`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Knjiga` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Knjiga` (
  `idKnjiga` INT NOT NULL AUTO_INCREMENT,
  `Naziv` VARCHAR(100) NULL,
  PRIMARY KEY (`idKnjiga`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Oblast`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Oblast` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Oblast` (
  `idOblast` INT NOT NULL,
  `Oblast_Knjiga` VARCHAR(45) NOT NULL,
  INDEX `idOblast_Knjiga_idx` (`idOblast` ASC),
  CONSTRAINT `idOblast_Knjiga`
    FOREIGN KEY (`idOblast`)
    REFERENCES `mydb`.`Knjiga` (`idKnjiga`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`KnjigaIzdavac`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`KnjigaIzdavac` ;

CREATE TABLE IF NOT EXISTS `mydb`.`KnjigaIzdavac` (
  `diKnjiga` INT NOT NULL,
  `idIzdavac` INT NOT NULL,
  `Godina` YEAR NOT NULL,
  `Tiraz` INT NOT NULL,
  INDEX `idKI_Izdavac_idx` (`idIzdavac` ASC),
  INDEX `idKI_Knjiga_idx` (`diKnjiga` ASC),
  CONSTRAINT `idKI_Izdavac`
    FOREIGN KEY (`idIzdavac`)
    REFERENCES `mydb`.`Izdavac` (`idIzdavac`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idKI_Knjiga`
    FOREIGN KEY (`diKnjiga`)
    REFERENCES `mydb`.`Knjiga` (`idKnjiga`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`KnjigaPisac`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`KnjigaPisac` ;

CREATE TABLE IF NOT EXISTS `mydb`.`KnjigaPisac` (
  `idKnjiga` INT NOT NULL,
  `idPISAC` INT NOT NULL,
  `R_Broj` INT NOT NULL,
  INDEX `idKP_Pisac_idx` (`idPISAC` ASC),
  INDEX `idKP_Knjiga_idx` (`idKnjiga` ASC),
  CONSTRAINT `idKP_Pisac`
    FOREIGN KEY (`idPISAC`)
    REFERENCES `mydb`.`PISAC` (`idPISAC`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idKP_Knjiga`
    FOREIGN KEY (`idKnjiga`)
    REFERENCES `mydb`.`Knjiga` (`idKnjiga`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
