DROP SCHEMA IF EXISTS `KIP` ;
CREATE SCHEMA IF NOT EXISTS `KIP` DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci ;
USE `KIP` ;

DROP TABLE IF EXISTS `KIP`.`K` ;
CREATE  TABLE IF NOT EXISTS `KIP`.`K`(
`idK` CHAR(5) NOT NULL, 
`Naslov` CHAR(50) NOT NULL, 
`Oblast` CHAR(20), 
PRIMARY KEY (`idK`)); 

CREATE  TABLE IF NOT EXISTS `KIP`.`I`(
`idI` CHAR(6) NOT NULL, 
`Naziv` CHAR(20) NOT NULL,
`Status` SMALLINT, 
`Drzava` CHAR(20) NOT NULL, 
PRIMARY KEY (`idI`));

CREATE  TABLE IF NOT EXISTS `KIP`.`P`(
`idP` CHAR(5) NOT NULL, 
`Ime` CHAR(50) NOT NULL, 
`BrNaslova` SMALLINT, 
`Drzava` CHAR(20) NOT NULL, 
PRIMARY KEY (`idP`));

CREATE  TABLE IF NOT EXISTS `KIP`.`KI`(
`idK` CHAR(5) NOT NULL, 
`idI` CHAR(6) NOT NULL, 
`Izdanje` SMALLINT NOT NULL, 
`Godina` SMALLINT, 
`Tiraz` INTEGER, 
PRIMARY KEY (`idK`, `idI`, `Izdanje`), 
FOREIGN KEY (`idK`) REFERENCES `KIP`.`K`(`idK`) ON DELETE RESTRICT ON UPDATE RESTRICT, 
FOREIGN KEY (`idI`) REFERENCES `KIP`.`I`(`idI`) ON DELETE CASCADE);

CREATE  TABLE IF NOT EXISTS `KIP`.`KP`(
`idK` CHAR(5) NOT NULL, 
`idP` CHAR(5) NOT NULL, 
`RBroj` SMALLINT NOT NULL, 
PRIMARY KEY (`idK`, `idP`),  
FOREIGN KEY (`idK`) REFERENCES `KIP`.`K`(`idK`) ON DELETE RESTRICT ON UPDATE  RESTRICT, 
FOREIGN KEY (`idP`) REFERENCES `KIP`.`P`(`idP`) ON DELETE CASCADE);