-- MySQL Script generated by MySQL Workbench
-- 04/22/16 09:29:39
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema vezba
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `vezba` ;

-- -----------------------------------------------------
-- Schema vezba
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vezba` DEFAULT CHARACTER SET utf8 ;
USE `vezba` ;

-- -----------------------------------------------------
-- Table `vezba`.`logovanje`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vezba`.`logovanje` ;

CREATE TABLE IF NOT EXISTS `vezba`.`logovanje` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ime` VARCHAR(45) NOT NULL,
  `prezime` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `slika` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
