-- MySQL Script generated by MySQL Workbench
-- 03/22/16 11:31:38
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Preduzece`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Preduzece` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Preduzece` (
  `idPreduzece` INT NOT NULL AUTO_INCREMENT,
  `Naziv` VARCHAR(45) NOT NULL,
  `Delatnost` VARCHAR(45) NOT NULL,
  `Adresa` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPreduzece`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Kupac`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Kupac` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Kupac` (
  `idKupac` INT NOT NULL AUTO_INCREMENT,
  `Ime` VARCHAR(45) NOT NULL,
  `Prezime` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `BrTelefona` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idKupac`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Proizvod`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Proizvod` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Proizvod` (
  `idProizvod` INT NOT NULL AUTO_INCREMENT,
  `Naziv` VARCHAR(45) NOT NULL,
  `idKupac` INT NOT NULL,
  PRIMARY KEY (`idProizvod`),
  INDEX `idProi_Kupac_idx` (`idKupac` ASC),
  CONSTRAINT `idProi_Kupac`
    FOREIGN KEY (`idKupac`)
    REFERENCES `mydb`.`Kupac` (`idKupac`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Radnik`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Radnik` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Radnik` (
  `idRadnik` INT NOT NULL AUTO_INCREMENT,
  `Ime` VARCHAR(45) NOT NULL,
  `Prezime` VARCHAR(45) NOT NULL,
  `JMBG` INT NOT NULL,
  `idpreduzece` INT NOT NULL,
  `idProizvod` INT NOT NULL,
  PRIMARY KEY (`idRadnik`),
  INDEX `idRadnik_Preduzece_idx` (`idpreduzece` ASC),
  INDEX `idRadnik_Proizvod_idx` (`idProizvod` ASC),
  CONSTRAINT `idRadnik_Preduzece`
    FOREIGN KEY (`idpreduzece`)
    REFERENCES `mydb`.`Preduzece` (`idPreduzece`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idRadnik_Proizvod`
    FOREIGN KEY (`idProizvod`)
    REFERENCES `mydb`.`Proizvod` (`idProizvod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Kategorija`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Kategorija` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Kategorija` (
  `PKNaziv` INT NOT NULL,
  `Opis` VARCHAR(45) NOT NULL,
  CONSTRAINT `kategorija_Proizvod`
    FOREIGN KEY (`PKNaziv`)
    REFERENCES `mydb`.`Proizvod` (`idProizvod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Racun`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Racun` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Racun` (
  `idRacun` INT NOT NULL AUTO_INCREMENT,
  `idProizvod` INT NOT NULL,
  `idRadnik` INT NOT NULL,
  `Vreme` DATETIME NOT NULL,
  PRIMARY KEY (`idRacun`),
  INDEX `Racun_Proizvod_idx` (`idProizvod` ASC),
  INDEX `Racun_Radnik_idx` (`idRadnik` ASC),
  CONSTRAINT `Racun_Proizvod`
    FOREIGN KEY (`idProizvod`)
    REFERENCES `mydb`.`Proizvod` (`idProizvod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Racun_Radnik`
    FOREIGN KEY (`idRadnik`)
    REFERENCES `mydb`.`Radnik` (`idRadnik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
