-- MySQL Script generated by MySQL Workbench
-- 02/29/16 11:12:49
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`vezba`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`vezba` ;

CREATE TABLE IF NOT EXISTS `mydb`.`vezba` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Polaznik`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Polaznik` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Polaznik` (
  `idPolaznik` INT NOT NULL AUTO_INCREMENT,
  `Ime` VARCHAR(45) NULL,
  `Prezime` VARCHAR(45) NULL,
  `datumRodjenja` DATE NULL,
  PRIMARY KEY (`idPolaznik`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Predavac`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Predavac` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Predavac` (
  `idPredavac` INT NOT NULL AUTO_INCREMENT,
  `Ime` VARCHAR(45) NULL,
  PRIMARY KEY (`idPredavac`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Kurs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Kurs` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Kurs` (
  `idKurs` INT NOT NULL AUTO_INCREMENT,
  `Naziv` VARCHAR(45) NULL,
  `FondCasova` INT NULL,
  PRIMARY KEY (`idKurs`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PolaznikKurs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`PolaznikKurs` ;

CREATE TABLE IF NOT EXISTS `mydb`.`PolaznikKurs` (
  `idPolaznikKurs` INT NOT NULL AUTO_INCREMENT,
  `Id_Polaznik` INT NULL,
  `Id_Kurs` INT NULL,
  `Dl` INT NULL,
  `Polozio` INT NULL,
  PRIMARY KEY (`idPolaznikKurs`),
  INDEX `ID_polaznikkurs_Strani_idx` (`Id_Kurs` ASC),
  INDEX `ID_polanikkurs_idKurs_idx` (`idPolaznikKurs` ASC, `Id_Kurs` ASC),
  CONSTRAINT `ID_polaznikkurs_Strani`
    FOREIGN KEY (`Id_Kurs`)
    REFERENCES `mydb`.`Polaznik` (`idPolaznik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ID_polanikkurs_idKurs`
    FOREIGN KEY (`idPolaznikKurs` , `Id_Kurs`)
    REFERENCES `mydb`.`Kurs` (`idKurs` , `idKurs`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PredavacKurs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`PredavacKurs` ;

CREATE TABLE IF NOT EXISTS `mydb`.`PredavacKurs` (
  `Id_PredavacKursa` INT NOT NULL AUTO_INCREMENT,
  `Id_Predavac` INT NULL,
  `Id_Kurs` INT NULL,
  PRIMARY KEY (`Id_PredavacKursa`),
  INDEX `ID_PK_Pola_idx` (`Id_Predavac` ASC),
  INDEX `ID_PK_Kurs_idx` (`Id_Kurs` ASC),
  CONSTRAINT `ID_PK_Predavac`
    FOREIGN KEY (`Id_Predavac`)
    REFERENCES `mydb`.`Predavac` (`idPredavac`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ID_PK_Kurs`
    FOREIGN KEY (`Id_Kurs`)
    REFERENCES `mydb`.`Kurs` (`idKurs`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
