INSERT into DRZAVA VALUES(1,'Jugoslavija');
INSERT into DRZAVA VALUES(2,'Engleska');
INSERT into DRZAVA VALUES(3,'Amerika');

INSERT into OBLAST VALUES(1,'roman');
INSERT into OBLAST VALUES(2,'poezija');
INSERT into OBLAST VALUES(3,'leksikografija');
INSERT into OBLAST VALUES(4,'racunarstvo');

INSERT into IZDAVAC_STATUS VALUES(1,10);
INSERT into IZDAVAC_STATUS VALUES(2,20);
INSERT into IZDAVAC_STATUS VALUES(3,30);

INSERT into PISAC VALUES(1,'Branko','Copic',2,1);
INSERT into PISAC VALUES(2,'Morton','Benson',1,3);
INSERT into PISAC VALUES(3,'Biljana','Sljivic-Simsic',1,1);
INSERT into PISAC VALUES(4,'Danica','Maksimovic',2,1);
INSERT into PISAC VALUES(5,'Christopher','J.Date',1,2);

INSERT into IZDAVAC VALUES(1,'Prosveta',3,1);
INSERT into IZDAVAC VALUES(2,'Addison Wesley',2,3);
INSERT into IZDAVAC VALUES(3,'Decje novine',1,1);
INSERT into IZDAVAC VALUES(4,'Matica srpska',3,1);

INSERT into KNJIGA VALUES(1,'Osma ofanziva',1);
INSERT into KNJIGA VALUES(2,'Nemam vise vremena',2);
INSERT into KNJIGA VALUES(3,'Pionirska trilogija',1);
INSERT into KNJIGA VALUES(4,'Srpskohrvatsko-engleski recnik',3);
INSERT into KNJIGA VALUES(5,'An Introduction to Database Systems',4);
INSERT into KNJIGA VALUES(6,'Trazim pomilovanje',2);


INSERT into KNJIGA_PISAC VALUES(1,1,1);
INSERT into KNJIGA_PISAC VALUES(2,4,1);
INSERT into KNJIGA_PISAC VALUES(3,1,1);
INSERT into KNJIGA_PISAC VALUES(4,3,2);
INSERT into KNJIGA_PISAC VALUES(5,5,1);
INSERT into KNJIGA_PISAC VALUES(6,4,1);


INSERT into KNJIGA_IZDAVAC VALUES(1,1,1,1965,10000);
INSERT into KNJIGA_IZDAVAC VALUES(2,1,2,1974,7000);
INSERT into KNJIGA_IZDAVAC VALUES(3,1,1,1975,10000);
INSERT into KNJIGA_IZDAVAC VALUES(4,1,2,1979,10000);
INSERT into KNJIGA_IZDAVAC VALUES(5,2,4,1986,5000);
INSERT into KNJIGA_IZDAVAC VALUES(6,3,1,1966,3000);
INSERT into KNJIGA_IZDAVAC VALUES(6,4,3,1988,5000);

